import Head from 'next/head';
import { Inter } from 'next/font/google';
import Header from '@/components/header/Header'; // component import
import Banner from '@/components/banner/Banner';
import HomeFeed from '@/components/homefeed/HomeFeed';
import BottomSignInBtn from '@/components/homefeed/pc_screen_feed/pc_screen_feed_component/BottomSignInBtn';
import BackToTop from '@/components/homefeed/pc_screen_feed/pc_screen_feed_component/BackToTop';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div className='bg-amazon_home_background_color-dark_white pb-5'>
      <Head>
        <title>Amazon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header />

      {/* main */}
      <main className='max-w-screen-2xl mx-auto'> 
        {/* Banner */}
        <Banner />

        {/* Home Feed */}
        <HomeFeed />
      </main>
      
      {/* Bottom Signin Button Incator that user go for a signin tour start */}
      <BottomSignInBtn />
      {/* Bottom Signin Button Incator that user go for a signin tour end */}

      {/* Back to Top button ( navigate top of the container ) start */}
      <BackToTop />
      {/* Back to Top button ( navigate top of the container ) start */}
      
      
    </div>
  )
}
