import Head from 'next/head';
import { Inter } from 'next/font/google';
import Header from '@/components/header/Header'; // component import
import Banner from '@/components/banner/Banner';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Amazon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header />

      {/* main */}
      <main className='max-w-screen-2xl mx-auto bg-amazon_home_background_color-dark_white'> 
        {/* Banner */}
        <Banner />

        {/* Home Feed */}
      </main>
      
      
    </>
  )
}
