import Head from 'next/head'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Amazon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='w-full h-screen flex flex-col items-center justify-center'>
        <h1 className='text-xl text-red-700 font-bold'>Hello World</h1>
        <h1 className='text-lg font-normal'>We are building Amazon Clone app</h1>
      </div>
      
    </>
  )
}
